gods/gods/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from goddesses.views import page_not_found
from gods import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goddesses.urls')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = 'Admin panel'
admin.site.index_title = 'Site about deities'

gods/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout')
]

gods/templates/base.html
{% load static %}
{% load gods_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|upper }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'goddesses/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="{% static 'goddesses/css/styles.css' %}" rel="stylesheet"/>
</head>

<body>
<table class="table-content" border=0 cellpadding="0" cellspacing="0">
    <tr>
        <td valign=top>

            {% block mainmenu %}
            <div class="header">
                <ul id="mainmenu" class="mainmenu">
                    <li><a href="{% url 'home' %}">Home</a></li>

                    {% for item in mainmenu  %}
<!--                        {% if not forloop.last %}<li>{% else %}<li class="last">{% endif %}-->
                         <li>   <a href="{% url item.url_name %}"> {{ item.title }} </a>      </li>
                    {% endfor %}
                    {% if user.is_authenticated %}
                        <li class="last"> {{user.username}} | <a href="{% url 'users:logout' %}"> Logout </a> </li>
                    {% else %}
                        <li class="last"><a href="{% url 'users:login' %}"> Login </a> | <a href="#"> Register </a></li>
                    {% endif %}
                </ul>
                <div class="clear"></div>
            </div>
            {% endblock mainmenu %}

            <table class="table-content" border=0 cellpadding="0" cellspacing="0">
                <tr>


                    <!-- Sidebar слева -->
                    <td valign="top" class="left-chapters">
                        <ul id="leftchapters">
                            {% if cat_selected == 0 %}
                                <li class="selected">All categories</li>
                            {% else %}
                                <li><a href="{% url 'home' %}">All categories</a></li>
                            {% endif %}

                            {% show_categories cat_selected %}

                            <li>{% show_tags %}</li>
                        </ul>
                    </td>
                    <!-- Конец Sidebar'а -->

                    <!-- Блок контента -->
                    <td valign="top" class="content">
                        <div class="content-text">
                            {% block content %}
                            {% endblock %}
                        </div>
                        {% block navigation %}
                        {% endblock %}
                    </td>
                    <!-- Конец блока контента -->

                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>